/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sapient.client.gui;
import java.math.BigDecimal;
import java.sql.*;

import javax.swing.JOptionPane;

/**
 *
 * @author agu182
 */
public class EmployeeDetails extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDetails
     */
    public EmployeeDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeeID = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Salary = new javax.swing.JLabel();
        EmplyeeID = new javax.swing.JTextField();
        FirName = new javax.swing.JTextField();
        LstName = new javax.swing.JTextField();
        Salry = new javax.swing.JTextField();
        FindById = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Modify = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EmployeeID.setText("Emplyee ID");

        FirstName.setText("First Name");

        LastName.setText("Last Name");

        Salary.setText("Salary");

        FirName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirNameActionPerformed(evt);
            }
        });

        LstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LstNameActionPerformed(evt);
            }
        });

        FindById.setText("Find By ID");
        FindById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindByIdActionPerformed(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Modify.setText("Modify");
        Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyActionPerformed(evt);
            }
        });

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmployeeID, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FirstName))
                                .addGap(69, 69, 69))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Salary)
                                    .addComponent(LastName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(FindById)
                        .addGap(26, 26, 26)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FirName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(EmplyeeID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LstName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Salry, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Modify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(Remove)
                        .addGap(26, 26, 26)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeID)
                    .addComponent(EmplyeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName)
                    .addComponent(FirName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName)
                    .addComponent(LstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salary)
                    .addComponent(Salry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FindById)
                    .addComponent(Add)
                    .addComponent(Modify)
                    .addComponent(Remove)
                    .addComponent(Exit))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirNameActionPerformed

    private void LstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LstNameActionPerformed

    private void FindByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindByIdActionPerformed
                 // TODO add your handling code here:
    	CallableStatement cStatement=null;
    	 Connection  dbConnection=null;
		try{  DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
  	   dbConnection=DriverManager.getConnection("jdbc:oracle:thin:@deltahiti31202:1521:XE", "ADITI","aditi123");
    	 cStatement=dbConnection.prepareCall("{call query_emp(?,?,?,?)}");
    	 cStatement.setInt(1,Integer.parseInt(EmplyeeID.getText()));
    	 cStatement.setString(2,(FirName.getText()));
    	 cStatement.setInt(3,(Integer.parseInt(Salry.getText())));
    	
   
    	 cStatement.registerOutParameter(2, java.sql.Types.VARCHAR);
    	 cStatement.registerOutParameter(3, java.sql.Types.DECIMAL);
    	 cStatement.registerOutParameter(4, java.sql.Types.DECIMAL);
    	 cStatement.execute();
    	 String empName=cStatement.getString(2);
    	 BigDecimal empSal=cStatement.getBigDecimal(3);
    	 //BigDecimal empComm=cStatement.getBigDecimal(4);
    	 FirName.setText(empName);
		  LstName.setText(empSal.toString());
		  
    	 
    	 }catch(SQLException e){
   		  e.printStackTrace();
   	  }
   	finally{
   		try{
   		if(dbConnection!=null && !dbConnection.isClosed())
   		{
   			dbConnection.close();
   			
   		}
   		if(cStatement!=null )
   		{
   			cStatement.close();
   			
   		}
   		}catch(SQLException e){
   			e.printStackTrace();
   		}

}
    	
    	
    	
    	/*Connection dbConnection=null;
    	PreparedStatement pStatement = null;
    	ResultSet result = null;
    	 try{  DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
    	   dbConnection=DriverManager.getConnection("jdbc:oracle:thin:@deltahiti31202:1521:XE", "ADITI","aditi123");
    	   pStatement=dbConnection.prepareStatement("SELECT  FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID=?");
    	   pStatement.setInt(1,Integer.parseInt(EmplyeeID.getText()));
    	   result=pStatement.executeQuery();
    	  if( result.next()){
    		  FirName.setText(result.getString(1));
    		  LstName.setText(result.getString(2));
    		  Salry.setText(result.getString(3));
    	  }
    	  else{
    		  JOptionPane.showMessageDialog(this, "no record found","Emplotyee id does not exist",JOptionPane.ERROR_MESSAGE);
    		  
    	  }}catch(SQLException e){
    		  e.printStackTrace();
    	  }
    	finally{
    		try{
    		if(dbConnection!=null && !dbConnection.isClosed())
    		{
    			dbConnection.close();
    			
    		}
    		if(pStatement!=null )
    		{
    			pStatement.close();
    			
    		}
    		if(result!=null )
    		{
    			result.close();
    			
    		}}catch(SQLException e){
    			e.printStackTrace();
    		}
    	}*/
}

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    	Connection dbConnection=null;
    	PreparedStatement pStatement = null;
    	
    	 try{  
    		 DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
    	   dbConnection=DriverManager.getConnection("jdbc:oracle:thin:@deltahiti31202:1521:XE", "ADITI","aditi123");
    	   pStatement=dbConnection.prepareStatement("INSERT INTO EMPLOYE VALUES(?,?,?,?) ");
    	   
    	   pStatement.setInt(1,(Integer.parseInt(EmplyeeID.getText())));
    	  pStatement.setString(2,FirName.getText());
    	  pStatement.setString(3,LstName.getText());
    	  pStatement.setInt(4,Integer.parseInt(Salry.getText()));
    	
    	   int response =pStatement.executeUpdate();
    	  if( response!=0){
    		  JOptionPane.showMessageDialog(this, "Data has been updated","New Employee data has been added",JOptionPane.INFORMATION_MESSAGE);	;
    	  }
    	  else{
    		  JOptionPane.showMessageDialog(this, "no record found","Emplotyee id does not exist",JOptionPane.ERROR_MESSAGE);
    		  
    	  }}catch(SQLException e){
    		  e.printStackTrace();
    	  }
    	finally{
    		try{
    		if(dbConnection!=null && !dbConnection.isClosed())
    		{
    			dbConnection.close();
    			
    		}
    		if(pStatement!=null )
    		{
    			pStatement.close();
    			
    		}
    		/*if(result!=null )
    		{
    			result.close();
    			
    		}*/}catch(SQLException e){
    			e.printStackTrace();
    		}
    	}
    	
    }//GEN-LAST:event_AddActionPerformed

    private void ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyActionPerformed
        // TODO add your handling code here:
    	Connection dbConnection=null;
    	PreparedStatement pStatement = null;
    	
    	 try{  
    		 DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
    	   dbConnection=DriverManager.getConnection("jdbc:oracle:thin:@deltahiti31202:1521:XE", "ADITI","aditi123");
    	   pStatement=dbConnection.prepareStatement("UPDATE  EMPLOYE SET FIRST_NAME=?,LAST_NAME=?,SALARY=? WHERE EMPLOYEE_ID=?");
    	   
    	 
    	  pStatement.setString(1,FirName.getText());
    	  pStatement.setString(2,LstName.getText());
    	  pStatement.setInt(3,(Integer.parseInt(Salry.getText())));
    	  pStatement.setInt(4,(Integer.parseInt(EmplyeeID.getText())));
    	   int response =pStatement.executeUpdate();
    	  if( response!=0){
    		  JOptionPane.showMessageDialog(this, "Data has been updated"," Employee data has been modified",JOptionPane.INFORMATION_MESSAGE);	
    	  }
    	  else{
    		  JOptionPane.showMessageDialog(this, "no record found","Emplotyee id does not exist",JOptionPane.ERROR_MESSAGE);
    		  
    	  }}catch(SQLException e){
    		  e.printStackTrace();
    	  }
    	finally{
    		try{
    		if(dbConnection!=null && !dbConnection.isClosed())
    		{
    			dbConnection.close();
    			
    		}
    		if(pStatement!=null )
    		{
    			pStatement.close();
    			
    		}
    		/*if(result!=null )
    		{
    			result.close();
    			
    		}*/}catch(SQLException e){
    			e.printStackTrace();
    		}
    	}
    	
    }
    //GEN-LAST:event_ModifyActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel EmployeeID;
    private javax.swing.JTextField EmplyeeID;
    private javax.swing.JButton Exit;
    private javax.swing.JButton FindById;
    private javax.swing.JTextField FirName;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LstName;
    private javax.swing.JButton Modify;
    private javax.swing.JButton Remove;
    private javax.swing.JLabel Salary;
    private javax.swing.JTextField Salry;
    // End of variables declaration//GEN-END:variables
}
